name: Create Discussion on Post Creation

on:
  repository_dispatch:
    types: [create_discussion]
    
jobs:
  create-discussion:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Create a new Discussion
          id: create-discussion
          uses: abirismyname/create-discussion@v1.x
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
            SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
            SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
            SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}
          with:
            title: '${{ github.event.client_payload.slug }}'
            body: |
              "Discusión creada para el post: [Ver post](https://tu-blog.com/posts/${{ github.event.client_payload.slug }})"
            repository-id: ${{ secrets.REPOSITORY_ID }}
            category-id: ${{ secrets.CATEGORY_ID }}  
        - name: Print discussion url and id
          run: |
            curl -X POST \
            -H "Authorization: Bearer $SANITY_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "mutations": [
                {
                  "patch": {
                    "id": "'"${{ github.event.client_payload._id }}"'",
                    "set": {
                      "discussionId": "'"${{ steps.create-discussion.outputs.discussion-id }}"'",
                    }
                  }
                }
              ]
            }' \
            https://$SANITY_PROJECT_ID.api.sanity.io/v1/data/mutate/$SANITY_DATASET

