name: Create Discussion on Post Creation

on:
  repository_dispatch:
    types: [create_discussion]
    
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  create-discussion:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - name: Create a new Discussion
          id: create-discussion
          uses: abirismyname/create-discussion@v1.x
          env:
            GH_TOKEN: ${{ secrets.TOKEN }}      
          with:
            title: '${{ github.event.client_payload.slug }}'
            body: |
              "Discusión creada para el post: [Ver post](https://tu-blog.com/posts/${{ github.event.client_payload.slug }})"
            repository-id: ${{ secrets.REPOSITORY_ID }}
            category-id: ${{ secrets.CATEGORY_ID }}  
        - name: Print discussion url and id
          run: |
            echo discussion-id: ${{steps.create-discussion.outputs.discussion-id}} 
            echo discussion-url: ${{steps.create-discussion.outputs.discussion-url}}    

