name: Create Discussion on Post Creation

on:
  repository_dispatch:
    types: [manage_discussion]
    
jobs:
  create-discussion:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install jq
          run: |
            sudo apt-get update
            sudo apt-get install -y jq
  
        - name: Print GitHub Event
          run: |
            echo '${{ toJson(github.event) }}' | jq .

