name: Create Discussion on Post Creation

on:
  repository_dispatch:
    types: [create_discussion]
    
jobs:
  create-discussion:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Create a new Discussion
          id: create-discussions
          run: |
            echo '${{ github.event }}'

