name: Create Discussion on Post Creation

on:
  repository_dispatch:
    types: [create_discussion]

jobs:
  create-discussion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          node-version: '20'

      - name: Create GitHub Discussion
        id: create-discussion
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          CATEGORY_ID: ${{ secrets.CATEGORY_ID }}
        run: |
          response=$(curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "query": "mutation ($repoId: ID!, $title: String!, $body: String!, $categoryId: ID!) {
                createDiscussion(input: {
                  repositoryId: $repoId,
                  title: $title,
                  categoryId: $categoryId
                  body: $body
                }) {
                  discussion {
                    id
                    url
                  }
                }
              }",
              "variables": {
                "repoId": "'"$GITHUB_REPOSITORY_ID"'",
                "categoryId": "'"$CATEGORY_ID"'",
                "title": "Comentarios para: '${{ github.event.client_payload.slug }}'",
                "body": "Discusión creada para el post: [Ver post](https://tu-blog.com/posts/${{ github.event.client_payload.slug }})"
              }
            }' \
            https://api.github.com/graphql)
      - name: Debug Response
        run: |
          echo "Response: $response"

