name: Manage Discussions for Post Events

on:
  repository_dispatch:
    types: [create_discussion]

jobs:
  manage-discussions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Discussion
        id: create-discussion
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_ID: ${{ secrets.REPOSITORY_ID }}
          CATEGORY_ID: ${{ secrets.CATEGORY_ID }}
          TITLE: ${{ github.event.client_payload.slug }}
          BODY: "Post at: (https://robomous.ai/blog/${{ github.event.client_payload.slug }})"

        run: |
          payload=$(jq -n --arg repoId "$REPO_ID" \
                           --arg categoryId "$CATEGORY_ID" \
                           --arg title "$TITLE" \
                           --arg body "$BODY" \
                           '{
                             query: "mutation ($repoId: ID!, $categoryId: ID!, $title: String!, $body: String!) {
                               createDiscussion(input: {
                                 repositoryId: $repoId,
                                 categoryId: $categoryId,
                                 title: $title,
                                 body: $body
                               }) {
                                 discussion {
                                   id
                                   number
                                 }
                               }
                             }",
                             variables: {
                               repoId: $repoId,
                               categoryId: $categoryId,
                               title: $title,
                               body: $body
                             }
                           }')

          response=$(curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$payload" \
            https://api.github.com/graphql)

          discussionId=$(echo "$response" | jq -r '.data.createDiscussion.discussion.id')
          discussionNum=$(echo "$response" | jq -r '.data.createDiscussion.discussion.number')

          if [ -z "$discussionId" ] || [ "$discussionId" == "null" ]; then
            echo "Error: Failed to create discussion."
            exit 1
          fi

          echo "discussion_id=$discussionId" >> $GITHUB_OUTPUT
          echo "discussion_num=$discussionNum" >> $GITHUB_OUTPUT

      - name: Update Sanity with Discussion ID
        env:
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}
          DOCUMENT_ID: ${{ github.event.client_payload._id }}
          DISCUSSION_ID: ${{ steps.create-discussion.outputs.discussion_id }}
          DISCUSSION_NUM: ${{ steps.create-discussion.outputs.discussion_num }}
        run: |
            payload=$(jq -n --arg id "$DOCUMENT_ID" \
                             --arg discussionId "$DISCUSSION_ID" \
                             --arg discussionNum "$DISCUSSION_NUM" \
                             '{
                               mutations: [
                                 {
                                   patch: {
                                     id: $id,
                                     set: {
                                       discussionId: $discussionId,
                                       discussionNumber: $discussionNum
                                     }
                                   }
                                 }
                               ]
                             }')
  
            curl -X POST \
              -H "Authorization: Bearer $SANITY_TOKEN" \
              -H "Content-Type: application/json" \
              -d "$payload" \
              https://$SANITY_PROJECT_ID.api.sanity.io/v1/data/mutate/$SANITY_DATASET  